### PR TITLE
[Looking for someone to maintain] Add Initial Japanese README

### PR DESCRIPTION
**Pull request by jules2689**
Since a lot of the Ruby community is Japanese, I wanted to experiment with providing a Japanese README.

This translation is a little bit outdated since I took the README from a little while ago and paid for a translation. It was then corrected by a coworker who speaks/writes Japanese.

To make this a success, we likely need a bilingual person who is interested in OSS contributions that can help us maintain the Japanese README

### CODE REVIEW

**Comment by yuki24** [comment]
calling my bilingual developer friends @iumehara @take @djjimba

anyone interested?

**Comment by javierhonduco** [comment]
That's an awesome idea!! I'm wondering if @JuanitoFatas knows somebody that would be interested!

**Comment by JuanitoFatas** [comment]
@yasulab maybe interested?

**Comment by toshi0607** [comment]
Hi! Is the scope of this project translating [this README](https://github.com/Shopify/bootsnap/blob/master/README.md) into Japanese? 

I'm Japanese engineer and interested in that!

**Comment by jules2689** [comment]
@toshi0607 yes it is! We have an initial copy up (it's a bit outdated now) that was translated by a professional service and corrected by a friend of mine.

I'm hoping to find someone who could correct it on an ongoing basis. Are you up for that?

**Comment by yuki24** [comment]
I just [sent a PR](https://github.com/Shopify/bootsnap/pull/127) to the branch `readme-jp`. It's already somewhat outdated since I worked on it a few months ago, but I don't think that's a bad start.

**Comment by jules2689** [comment]
I am willing to merge the PR as is, and ping people to review when required... does that sound good?

**Comment by toshi0607** [comment]
@jules2689  It sounds good! I'm willing to check new PRs 

In addition to that ,I try to check the diffs of [@yuki24 's PR](https://github.com/Shopify/bootsnap/pull/127) and the newest READM written in English. If there would be points those are outdated, I'll send PR on this Friday.

**Pull request merged**
