### PR TITLE
Added preliminary Windows compatibility

### PR DESCRIPTION
**Pull request by daniel-rikowski**
These changes make it possible to use bootsnap on Windows. See #52 for discussion.

### CODE REVIEW

**Comment by burke** [comment]
This is much less extra code than I expected. Awesome! Definitely ok with merging this if you can figure out some reasonably sensible implementation for the `os_version` field.

**Comment by daniel-rikowski** [comment]
At the very least it should return zero. That's an obvious bug... 😨 

I'm now returning the result of `GetVersion`, it contains the major and minor version and the build number of Windows, squashed into a uint32_t.

**Comment by jules2689** [comment]
Yea, thanks a lot for this! Glad this can be expanded to all windows devs too!

**Comment by janpio** [comment]
Can/should Windows support be added to the README?

**Comment by Inversion-des** [comment]
How should we use it on Windows?
`supported?` returns `false` due to `RUBY_PLATFORM =~ /darwin|linux|bsd/`

I tested that for my app on Ruby 2.6.3 `compile_cache_iseq: true` works and reduces loading time for -36%, which is great.

Tried also `load_path_cache: true` but it just stuck with 100% CPU usage.

**Comment by daniel-rikowski** [comment]
The `supported?` check disabling Bootsnap on Windows was added about 18 months after the actual Windows support was merged. I'm not sure why that was added, I assume the intention was to "formalize" the default setup, which never enabled the compile cache on Windows. (Although no reason for that after Windows was added) (https://github.com/Shopify/bootsnap/commit/464104800277cb92022701608095583c3e1cc725)

I've been using Bootsnap on Windows ever since, now on Ruby 2.7.1 and Rails 6. (with `supported?` changed to return true on Windows)

@Inversion-des I don't know what is causing that, it should work. Whenever I suspect any Bootsnap "weirdness" I just delete the Bootsnap cache (on Rails it is in `tmp/cache`)

**Pull request merged**
