### PR TITLE
Document BOOTSNAP_CACHE_DIR environment variable

### PR DESCRIPTION
**Pull request by avdi**

### CODE REVIEW

**Review by casperisfine — APPROVED** [review]
Makes sense thank you. Unfortunately I'm afraid I can't merge without the CLA thing cleared out :/

If that annoys you I just commit this change myself.

**Comment by avdi** [comment]
What's a CLA? 

—
Avdi Grimm

--- original message ---
On Tue, Dec 8 at 03:59 AM, <notifications@github.com> Jean byroot Boussier wrote:



@casperisfine approved this pull request.

Makes sense thank you. Unfortunately I'm afraid I can't merge without the CLA thing cleared out :/

If that annoys you I just commit this change myself.

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by casperisfine** [comment]
> What's a CLA?

Contributor License Agreement (CLA), I know it's silly to ask for it for such a small README change but :/ 

See the failing CI status, it should be fairly quick to go through.

**Comment by avdi** [comment]
'k, done

**Pull request merged**
